export const NAV_LINKS = [
  { href: "/recipes", key: "recipes", label: "Recipes" },
  { href: "/", key: "about", label: "About" },
  { href: "/", key: "contact", label: "Contact" },
];

export const CATEGORIES = [
  {
    type: "entrees",
    color: "#59871f",
    background: "#f0f5c4",
    href: "/entrees",
  },
  {
    type: "breakfast",
    color: "#3c3a8f",
    background: "#efedfa",
    href: "/breakfast",
  },
  { type: "lunch", color: "#1f8787", background: "#e5f7f3", href: "/lunch" },
  {
    type: "desserts",
    color: "#397a9e",
    background: "#e8f5fa",
    href: "/desserts",
  },
  { type: "sides", color: "#d16400", background: "#feefc9", href: "/sides" },
  { type: "drinks", color: "#f0493e", background: "#ffeae3", href: "/drinks" },
];

export const MEALS: meal[] = [
  {
    mealId: 1,
    name: "Grilled Chicken Breast",
    thumbnail_image: "/meal-example.avif",
    category: "Entrees",
    instructions:
      "Season chicken breasts with salt, pepper, and olive oil. Grill over medium heat for 6-7 minutes on each side, or until fully cooked. Let rest before serving.",
    tags: ["Grilled", "Protein"],
    ingredients: [
      { name: "Chicken breast", quantity: "2 pieces" },
      { name: "Olive oil", quantity: "2 tbsp" },
      { name: "Salt", quantity: "to taste" },
      { name: "Black pepper", quantity: "to taste" },
    ],
    prep_time: "10 minutes",
    cook_time: "15 minutes",
    servings: "2",
    difficulty: "Easy",
  },
  {
    mealId: 2,
    name: "Pancakes",
    thumbnail_image: "/meal-example.avif",
    category: "Breakfast",
    instructions:
      "In a bowl, mix flour, milk, eggs, sugar, and baking powder until smooth. Heat a lightly oiled griddle over medium-high heat. Pour batter onto the griddle, using about 1/4 cup for each pancake. Cook until bubbles form and the edges are dry, then flip and cook until browned on the other side.",
    tags: ["Sweet", "Quick"],
    ingredients: [
      { name: "Flour", quantity: "1 cup" },
      { name: "Milk", quantity: "1 cup" },
      { name: "Eggs", quantity: "2" },
      { name: "Sugar", quantity: "2 tbsp" },
      { name: "Baking powder", quantity: "1 tbsp" },
      { name: "Butter", quantity: "for cooking" },
    ],
    prep_time: "10 minutes",
    cook_time: "10 minutes",
    servings: "4",
    difficulty: "Easy",
  },
  {
    mealId: 3,
    name: "Caesar Salad",
    thumbnail_image: "/meal-example.avif",
    category: "Lunch",
    instructions:
      "In a large bowl, combine romaine lettuce, croutons, and Parmesan cheese. In a separate small bowl, whisk together lemon juice, olive oil, anchovy paste, garlic, Dijon mustard, Worcestershire sauce, and salt. Pour the dressing over the salad and toss to combine. Serve immediately.",
    tags: ["Salad", "Healthy"],
    ingredients: [
      { name: "Romaine lettuce", quantity: "1 head" },
      { name: "Croutons", quantity: "1 cup" },
      { name: "Parmesan cheese", quantity: "1/2 cup, grated" },
      { name: "Lemon juice", quantity: "2 tbsp" },
      { name: "Olive oil", quantity: "1/4 cup" },
      { name: "Anchovy paste", quantity: "1 tsp" },
      { name: "Garlic", quantity: "1 clove, minced" },
      { name: "Dijon mustard", quantity: "1 tsp" },
      { name: "Worcestershire sauce", quantity: "1 tsp" },
      { name: "Salt", quantity: "to taste" },
    ],
    prep_time: "15 minutes",
    cook_time: "0 minutes",
    servings: "2",
    difficulty: "Medium",
  },
  {
    mealId: 4,
    name: "Chocolate Cake",
    thumbnail_image: "/meal-example.avif",
    category: "Desserts",
    instructions:
      "Preheat oven to 350°F (175°C). In a large bowl, combine flour, sugar, cocoa powder, baking powder, baking soda, and salt. Add eggs, milk, oil, and vanilla extract and mix until smooth. Pour into a greased and floured cake pan. Bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean. Let cool before serving.",
    tags: ["Sweet", "Baked"],
    ingredients: [
      { name: "Flour", quantity: "1 1/2 cups" },
      { name: "Sugar", quantity: "1 1/2 cups" },
      { name: "Cocoa powder", quantity: "3/4 cup" },
      { name: "Baking powder", quantity: "1 1/2 tsp" },
      { name: "Baking soda", quantity: "1 1/2 tsp" },
      { name: "Salt", quantity: "1/2 tsp" },
      { name: "Eggs", quantity: "2" },
      { name: "Milk", quantity: "1 cup" },
      { name: "Vegetable oil", quantity: "1/2 cup" },
      { name: "Vanilla extract", quantity: "2 tsp" },
    ],
    prep_time: "20 minutes",
    cook_time: "35 minutes",
    servings: "8",
    difficulty: "Medium",
  },
  {
    mealId: 5,
    name: "Garlic Mashed Potatoes",
    thumbnail_image: "/meal-example.avif",
    category: "Sides",
    instructions:
      "Peel and cut potatoes into chunks. Boil in salted water until tender, about 15 minutes. Drain and return to pot. Add butter, milk, and minced garlic. Mash until smooth. Season with salt and pepper to taste.",
    tags: ["Comfort Food", "Vegetarian"],
    ingredients: [
      { name: "Potatoes", quantity: "4 large" },
      { name: "Butter", quantity: "1/4 cup" },
      { name: "Milk", quantity: "1/2 cup" },
      { name: "Garlic", quantity: "3 cloves, minced" },
      { name: "Salt", quantity: "to taste" },
      { name: "Black pepper", quantity: "to taste" },
    ],
    prep_time: "10 minutes",
    cook_time: "15 minutes",
    servings: "4",
    difficulty: "Easy",
  },
  {
    mealId: 6,
    name: "Mojito",
    thumbnail_image: "/meal-example.avif",
    category: "Drinks",
    instructions:
      "In a glass, muddle mint leaves with sugar and lime juice. Add rum and fill the glass with ice. Top with soda water and stir gently. Garnish with a mint sprig and a lime wedge.",
    tags: ["Cocktail", "Refreshing"],
    ingredients: [
      { name: "Mint leaves", quantity: "10 leaves" },
      { name: "Sugar", quantity: "2 tsp" },
      { name: "Lime juice", quantity: "1 oz" },
      { name: "White rum", quantity: "2 oz" },
      { name: "Soda water", quantity: "to top" },
      { name: "Ice", quantity: "as needed" },
      { name: "Mint sprig", quantity: "for garnish" },
      { name: "Lime wedge", quantity: "for garnish" },
    ],
    prep_time: "5 minutes",
    cook_time: "0 minutes",
    servings: "1",
    difficulty: "Easy",
  },
];
